version: 1.0.{build}
image: Visual Studio 2022

environment:
  TAILSCALE_AUTH_KEY:tskey-auth-kLyKnntVpP11CNTRL-4GwQSmFFovDLcxfkJ27TwDER9SDzMpiVc
    secure: mJ+bI0YFHpvA4g/HaTK/XSRb1rdgzSlDReJqHnQPL8jeGORSvd4BNjQnUN+7boU2ZfOOmwclkCtkDBGOFLlyXQ==
  RDP_PASS: "PasswordKuat123!"

build_script:
  - ps: |
      Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
      Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
      
      $admin = [adsi]"WinNT://./appveyor,user"
      $admin.SetPassword($env:RDP_PASS)

      $tsInstaller = "$env:TEMP\tailscale-setup.exe"
      Invoke-WebRequest -Uri "https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe" -OutFile $tsInstaller
      Start-Process $tsInstaller -ArgumentList "/quiet", "/norestart" -Wait

      & "C:\Program Files\Tailscale\tailscale.exe" up --authkey=$env:TAILSCALE_AUTH_KEY --hostname=appveyor-rdp

      $tsIP = & "C:\Program Files\Tailscale\tailscale.exe" ip -4
      Write-Host "=========================================="
      Write-Host "IP Tailscale : $tsIP"
      Write-Host "Username     : appveyor"
      Write-Host "Password     : $env:RDP_PASS"
      Write-Host "=========================================="

      Start-Sleep -Seconds 3600
